CREATE TABLE
IF NOT EXISTS `track_animals`
(
`id` INT NULL,
`uid` INT NULL,
`name` VARCHAR
(MAX) NULL,
`type` VARCHAR
(MAX) NULL,
`breed` VARCHAR
(MAX) NULL,
`img` VARCHAR
(MAX) NULL,
`description` VARCHAR
(MAX) NULL,
`date_create` VARCHAR
(MAX) NULL
);

INSERT INTO track_animals
VALUES
    (1, 9, 'Gynko', 'cat', 'ginger', 'https://via.placeholder.com/400/743/fff/?text=Gynko', 'Occaecat quis dolore exercitation qui eiusmod magna fugiat amet ipsum. Consectetur sint aliquip deserunt nulla sunt mollit. Non aute consequat qui nulla. Aliqua ad elit aliquip officia ea.', NOW()),
    (2, 9, 'Twiist', 'horse', 'andalusian', 'https://via.placeholder.com/400/956/fff/?text=Twiist', 'Aliqua qui voluptate excepteur ut magna id occaecat sunt id tempor dolor laborum et. Proident minim incididunt dolor elit occaecat enim nisi. Nulla proident aliquip minim non do tempor laborum cillum officia reprehenderit duis irure dolor voluptate. Et ut irure nisi cupidatat officia nulla.', NOW()),
    (3, 5, 'Besto', 'dog', 'shitzu', 'https://via.placeholder.com/400/789/fff/?text=Besto', 'In laboris tempor ex id exercitation. Officia exercitation laboris laborum cillum reprehenderit minim mollit culpa cillum do amet qui consequat. Aute amet irure cupidatat cupidatat nulla eu eu exercitation laboris anim mollit. Enim quis irure dolore labore.', NOW()),
    (4, 4, 'Magneato', 'horse', 'draft', 'https://via.placeholder.com/400/701/fff/?text=Magneato', 'Labore officia pariatur nisi eiusmod ipsum laborum magna laboris labore esse nisi velit. Anim tempor cupidatat nulla aute laborum. Minim cillum ut pariatur cillum minim consectetur aliquip fugiat laborum proident. Magna sit minim qui labore esse laboris commodo eu.', NOW()),
    (5, 2, 'Terascape', 'cat', 'ginger', 'https://via.placeholder.com/400/887/fff/?text=Terascape', 'Reprehenderit mollit quis qui do incididunt adipisicing veniam Lorem incididunt irure dolor. Voluptate ipsum labore consectetur consectetur pariatur. Culpa quis mollit et nostrud labore eu ipsum ex culpa ipsum ex ipsum fugiat. Ea dolore aliqua ut dolore consequat minim labore nulla eu anim enim Lorem anim Lorem.', NOW()),
    (6, 9, 'Frolix', 'horse', 'draft', 'https://via.placeholder.com/400/831/fff/?text=Frolix', 'Dolor in Lorem enim amet cupidatat. Reprehenderit reprehenderit incididunt cupidatat dolor et ipsum nisi aliqua veniam minim. Quis pariatur pariatur enim fugiat consequat eiusmod ea cillum eiusmod excepteur tempor. Exercitation nulla amet irure occaecat tempor sunt.', NOW()),
    (7, 10, 'Pholio', 'cat', 'ginger', 'https://via.placeholder.com/400/997/fff/?text=Pholio', 'Id dolor aliqua culpa reprehenderit aute. Sunt veniam do fugiat consequat laboris Lorem consequat non dolor deserunt do nisi. Excepteur Lorem Lorem tempor aute ullamco elit ea consequat consectetur tempor enim non sit. Ullamco adipisicing dolore nisi excepteur eu ea est tempor incididunt minim dolore ad voluptate.', NOW()),
    (8, 9, 'Venoflex', 'dog', 'shitzu', 'https://via.placeholder.com/400/838/fff/?text=Venoflex', 'Ut amet anim elit elit. Nostrud tempor commodo veniam id ex fugiat aliquip magna incididunt id mollit. Ullamco enim nostrud fugiat ullamco consequat. Cupidatat exercitation reprehenderit esse ad voluptate id sunt anim eiusmod officia do excepteur non aliquip.', NOW()),
    (9, 5, 'Netagy', 'horse', 'shetland', 'https://via.placeholder.com/400/817/fff/?text=Netagy', 'Dolore eu occaecat do culpa Lorem ex Lorem duis. Est quis nulla occaecat ex tempor veniam in sunt id duis ex ipsum do magna. Ipsum ea deserunt dolore ullamco cupidatat adipisicing ad tempor in consectetur. Amet excepteur aute ad Lorem.', NOW()),
    (10, 7, 'Delphide', 'cat', 'calico', 'https://via.placeholder.com/400/993/fff/?text=Delphide', 'Nisi tempor nostrud aliqua eiusmod aliquip sunt Lorem nostrud exercitation mollit ut. Sit dolore dolor labore cupidatat magna enim commodo ullamco ex sit proident culpa. Reprehenderit do Lorem nostrud est proident esse ipsum duis elit enim cillum amet consectetur culpa. Sit voluptate cupidatat deserunt aute incididunt id.', NOW()),
    (11, 4, 'Tubesys', 'dog', 'golden retriever', 'https://via.placeholder.com/400/704/fff/?text=Tubesys', 'Commodo sunt reprehenderit non commodo ea velit et reprehenderit. Cupidatat incididunt veniam eu consectetur irure ullamco laboris aute amet ea. Reprehenderit consequat non occaecat reprehenderit pariatur commodo consectetur mollit culpa et sit pariatur. Adipisicing laborum exercitation velit minim occaecat eiusmod laboris anim.', NOW()),
    (12, 7, 'Bisba', 'horse', 'unicorn', 'https://via.placeholder.com/400/716/fff/?text=Bisba', 'Qui aliquip sit nostrud ipsum aliqua eiusmod ea fugiat proident tempor labore non. Aliqua duis Lorem do dolore ex occaecat eiusmod aliqua deserunt pariatur. Consequat ea ex fugiat aliqua officia proident eiusmod consectetur laboris in dolor sunt proident. Do ex ad ut ad elit Lorem et ex nisi magna cupidatat pariatur.', NOW()),
    (13, 9, 'Genekom', 'horse', 'unicorn', 'https://via.placeholder.com/400/784/fff/?text=Genekom', 'Occaecat eu amet est voluptate consectetur incididunt qui velit cupidatat consequat. Quis ea cillum nisi exercitation voluptate qui consequat consectetur Lorem enim aute non. Culpa elit nisi minim nisi sit id. Nisi occaecat elit ullamco consequat fugiat ullamco enim ipsum reprehenderit velit.', NOW()),
    (14, 3, 'Lotron', 'dog', 'golden retriever', 'https://via.placeholder.com/400/933/fff/?text=Lotron', 'Dolore fugiat laboris ea duis proident ullamco ex irure culpa incididunt. Duis Lorem laborum et ad velit aliquip. Officia id magna adipisicing aliqua nisi pariatur quis nulla consequat. Pariatur incididunt laboris nulla mollit.', NOW()),
    (15, 6, 'Talendula', 'cat', 'ginger', 'https://via.placeholder.com/400/846/fff/?text=Talendula', 'Esse ullamco minim eiusmod culpa deserunt magna proident laborum officia non deserunt incididunt voluptate amet. Deserunt nulla duis ea exercitation amet excepteur deserunt et sint sint cupidatat voluptate officia qui. Eu occaecat commodo minim occaecat ea nulla anim minim consequat. Proident ea elit eu excepteur sunt ut minim.', NOW()),
    (16, 9, 'Translink', 'horse', 'draft', 'https://via.placeholder.com/400/833/fff/?text=Translink', 'Ex nulla cillum aute ad proident ullamco pariatur commodo fugiat minim id. Anim consectetur labore sint aliquip ut labore ullamco minim velit nisi. Minim consectetur duis ipsum consectetur consequat et labore aute consectetur. Non aute adipisicing ea nulla ut excepteur dolor dolore nostrud nulla ut excepteur incididunt ad.', NOW()),
    (17, 2, 'Uniworld', 'horse', 'andalusian', 'https://via.placeholder.com/400/783/fff/?text=Uniworld', 'Elit proident id velit quis nostrud Lorem velit nostrud dolore consequat consectetur aute commodo exercitation. Sunt elit cillum dolor pariatur laborum velit. Commodo non Lorem duis qui ullamco dolor minim in et exercitation eu eu incididunt ex. Officia non excepteur velit ullamco eu culpa voluptate ad ea magna elit nisi proident.', NOW()),
    (18, 9, 'Colaire', 'dog', 'shitzu', 'https://via.placeholder.com/400/785/fff/?text=Colaire', 'Amet qui dolore incididunt ex ad non do voluptate laboris fugiat. Sint sint occaecat minim id labore occaecat mollit laborum adipisicing in culpa incididunt ex. Aliqua laboris reprehenderit et in excepteur nisi mollit ullamco sit nisi sit sit sunt. Occaecat esse occaecat duis irure.', NOW()),
    (19, 5, 'Imageflow', 'horse', 'draft', 'https://via.placeholder.com/400/805/fff/?text=Imageflow', 'Ipsum reprehenderit laboris ullamco labore est adipisicing ex nulla irure et sunt aute. Id commodo qui duis laborum occaecat ut est officia et proident amet est sit et. Velit cillum cupidatat labore eiusmod duis dolore consectetur non nostrud Lorem fugiat. Non non officia elit cillum.', NOW()),
    (20, 1, 'Acumentor', 'cat', 'ginger', 'https://via.placeholder.com/400/838/fff/?text=Acumentor', 'Cupidatat et dolore non id in amet commodo fugiat. Non duis laborum labore velit cillum Lorem. Veniam labore adipisicing ex in veniam. Ipsum magna commodo dolor dolore proident Lorem tempor incididunt magna.', NOW()),
    (21, 3, 'Octocore', 'horse', 'unicorn', 'https://via.placeholder.com/400/782/fff/?text=Octocore', 'Ipsum dolore cupidatat labore non. Occaecat quis velit dolore Lorem officia duis adipisicing do mollit enim. Occaecat reprehenderit proident aliquip enim sunt mollit. Occaecat irure quis veniam consequat dolor ad dolore est nisi.', NOW()),
    (22, 2, 'Slofast', 'dog', 'golden retriever', 'https://via.placeholder.com/400/728/fff/?text=Slofast', 'Eu anim reprehenderit proident adipisicing laborum mollit consequat ex. Ut commodo magna minim ex ad do eiusmod. Ut commodo ut excepteur est mollit. Cillum dolore reprehenderit amet proident eu cillum eiusmod labore proident.', NOW()),
    (23, 10, 'Mitroc', 'dog', 'golden retriever', 'https://via.placeholder.com/400/889/fff/?text=Mitroc', 'Occaecat deserunt consectetur qui ullamco labore occaecat do. Ex deserunt dolore culpa pariatur veniam mollit commodo voluptate tempor deserunt voluptate dolore irure ex. Eiusmod amet veniam laborum mollit enim cillum dolore exercitation fugiat cillum sint velit. Amet exercitation enim exercitation adipisicing do.', NOW()),
    (24, 9, 'Vetron', 'dog', 'golden retriever', 'https://via.placeholder.com/400/718/fff/?text=Vetron', 'Consectetur velit aliquip eu amet ut dolore id veniam tempor ullamco nulla. Nisi eu officia ea nostrud incididunt ad id. Tempor excepteur voluptate laborum ad nisi sunt consectetur id Lorem dolor. Adipisicing occaecat esse velit elit labore amet.', NOW()),
    (25, 7, 'Enersol', 'horse', 'shetland', 'https://via.placeholder.com/400/713/fff/?text=Enersol', 'Ipsum veniam eiusmod minim elit ea commodo laborum nostrud esse veniam. In velit sint laboris duis mollit qui proident consequat sint. Commodo anim do incididunt labore sit Lorem fugiat dolore veniam eu quis dolore. Reprehenderit minim eiusmod dolore non deserunt sunt ex elit sint enim elit aliqua culpa.', NOW()),
    (26, 4, 'Valreda', 'cat', 'ginger', 'https://via.placeholder.com/400/978/fff/?text=Valreda', 'Qui minim id laborum velit nulla id in occaecat nisi reprehenderit pariatur. Mollit labore aliquip velit dolore veniam aliqua ipsum ut elit Lorem. Ullamco qui culpa duis sunt velit minim et in ad laboris non. Excepteur adipisicing labore minim proident consequat excepteur adipisicing exercitation ut excepteur laboris sunt sit.', NOW()),
    (27, 7, 'Eplosion', 'cat', 'ginger', 'https://via.placeholder.com/400/941/fff/?text=Eplosion', 'Excepteur non enim id officia laboris incididunt laborum in tempor duis nostrud consectetur. Amet ut culpa do qui id mollit laboris. Duis deserunt tempor labore fugiat nulla irure velit dolore. Velit aute nisi culpa fugiat ex eu incididunt.', NOW()),
    (28, 2, 'Bristo', 'cat', 'ginger', 'https://via.placeholder.com/400/906/fff/?text=Bristo', 'Officia deserunt excepteur magna aute reprehenderit. Dolore ex do enim enim. Nisi nostrud mollit cupidatat cillum. Magna ipsum qui sit ut reprehenderit do consequat qui cillum Lorem.', NOW()),
    (29, 6, 'Combogene', 'dog', 'golden retriever', 'https://via.placeholder.com/400/840/fff/?text=Combogene', 'Fugiat nulla Lorem cillum non esse anim excepteur deserunt veniam exercitation laborum ipsum. Commodo labore mollit ut dolor in consectetur sit mollit veniam. Pariatur aliqua ea et occaecat irure ut. Anim consequat aute aliquip dolore proident adipisicing eiusmod.', NOW()),
    (30, 10, 'Helixo', 'horse', 'andalusian', 'https://via.placeholder.com/400/884/fff/?text=Helixo', 'Sit fugiat sint cillum anim anim adipisicing dolor nisi aute laborum tempor enim. Laboris quis amet veniam esse excepteur elit reprehenderit pariatur duis et. Velit labore non deserunt exercitation mollit occaecat reprehenderit. Ut eiusmod minim do et nulla ad voluptate commodo.', NOW()),
    (31, 10, 'Knowlysis', 'horse', 'shetland', 'https://via.placeholder.com/400/813/fff/?text=Knowlysis', 'Labore aliquip magna consequat Lorem est qui commodo voluptate ea. Cupidatat non labore consequat commodo nisi do tempor. Reprehenderit enim ad aliquip eu id fugiat velit proident eu eiusmod culpa ipsum voluptate. Magna cupidatat duis Lorem culpa ut sint commodo consequat aliquip quis veniam.', NOW()),
    (32, 1, 'Visualix', 'cat', 'shorthair', 'https://via.placeholder.com/400/981/fff/?text=Visualix', 'Nostrud pariatur tempor eiusmod anim laboris occaecat velit quis et occaecat nostrud dolor esse. Dolor labore commodo officia officia dolore magna ex qui laborum in. Consequat magna amet proident est aliquip veniam. Culpa et ipsum consectetur sint reprehenderit sunt esse aute eu.', NOW()),
    (33, 2, 'Oatfarm', 'dog', 'shitzu', 'https://via.placeholder.com/400/855/fff/?text=Oatfarm', 'Aliquip nisi anim aliquip eiusmod in deserunt amet sint aute proident reprehenderit quis. Commodo minim sunt velit aute commodo laborum eu. Sunt consectetur tempor sunt excepteur voluptate est deserunt exercitation non duis. Quis id minim laboris eiusmod eu tempor ut in.', NOW()),
    (34, 2, 'Velos', 'horse', 'shetland', 'https://via.placeholder.com/400/931/fff/?text=Velos', 'Ullamco ad fugiat eu laborum dolore esse quis aute eiusmod. Commodo culpa ut consectetur in ad commodo minim minim quis excepteur velit. Elit amet officia irure et et occaecat id Lorem sint qui duis veniam ea. Tempor proident veniam voluptate veniam quis incididunt irure esse id proident irure.', NOW()),
    (35, 2, 'Cubicide', 'horse', 'shetland', 'https://via.placeholder.com/400/981/fff/?text=Cubicide', 'Aute culpa sunt Lorem ex minim consequat dolor sint nulla ullamco eu voluptate eiusmod culpa. Dolore amet esse ut et. Id quis aute consequat reprehenderit sint consequat amet magna aliqua officia elit. Tempor ut laboris minim Lorem magna aliqua ex excepteur velit ea duis deserunt officia ex.', NOW()),
    (36, 6, 'Verbus', 'cat', 'calico', 'https://via.placeholder.com/400/713/fff/?text=Verbus', 'Labore mollit sit Lorem velit pariatur laboris sint voluptate ullamco ex consectetur. Fugiat adipisicing elit consequat sit veniam tempor velit eiusmod velit esse ea dolore velit. Eiusmod occaecat Lorem aliqua minim nostrud consequat velit in ad labore et commodo aute. Eiusmod sunt reprehenderit ex aliqua.', NOW()),
    (37, 4, 'Proxsoft', 'cat', 'calico', 'https://via.placeholder.com/400/818/fff/?text=Proxsoft', 'Non cillum do consectetur aliqua sunt exercitation aliqua. Dolor aliqua in sint aliquip dolore minim. Consequat laborum id adipisicing pariatur culpa velit ex nulla sit. Amet consectetur ut ex veniam elit consequat fugiat adipisicing Lorem ut labore.', NOW()),
    (38, 7, 'Exposa', 'dog', 'golden retriever', 'https://via.placeholder.com/400/844/fff/?text=Exposa', 'Esse cillum irure incididunt labore mollit nulla aliquip nisi magna id exercitation cupidatat dolore excepteur. Sint ipsum ullamco magna pariatur deserunt aliqua do enim. Cupidatat exercitation mollit officia ut aliquip aliquip. Ut aute irure proident ex sunt ea in adipisicing quis aute.', NOW()),
    (39, 1, 'Cofine', 'dog', 'shitzu', 'https://via.placeholder.com/400/956/fff/?text=Cofine', 'Aliqua magna excepteur ut velit anim amet elit nostrud est occaecat culpa. Adipisicing cillum do veniam incididunt magna velit commodo anim adipisicing nisi consequat aute eiusmod anim. Magna excepteur eiusmod dolore officia. Qui dolor sit proident sit.', NOW()),
    (40, 5, 'Eventex', 'cat', 'shorthair', 'https://via.placeholder.com/400/915/fff/?text=Eventex', 'Pariatur id magna culpa et sit culpa sit laboris nulla ullamco quis id. Cillum deserunt voluptate adipisicing dolor duis aliquip reprehenderit. Consectetur minim sunt ut Lorem laborum elit elit in culpa dolore exercitation. Fugiat anim sint eu ullamco sint ad irure aliqua proident adipisicing culpa consectetur.', NOW()),
    (41, 2, 'Bitrex', 'cat', 'shorthair', 'https://via.placeholder.com/400/906/fff/?text=Bitrex', 'Labore laboris do aliqua irure deserunt ea in proident Lorem ipsum dolor cillum nulla. Commodo dolore fugiat reprehenderit deserunt exercitation. Esse dolore ipsum voluptate ea anim enim ipsum exercitation ea. Adipisicing elit nisi occaecat aliqua laboris irure sit et qui sunt.', NOW()),
    (42, 9, 'Immunics', 'horse', 'andalusian', 'https://via.placeholder.com/400/973/fff/?text=Immunics', 'Occaecat culpa minim enim fugiat anim occaecat elit nisi. Esse irure aliqua dolor aliqua culpa pariatur ea dolor qui ut officia laborum veniam. Esse qui voluptate voluptate dolor ullamco. Ex aute consectetur excepteur tempor deserunt voluptate nostrud aute deserunt.', NOW()),
    (43, 5, 'Beadzza', 'horse', 'draft', 'https://via.placeholder.com/400/746/fff/?text=Beadzza', 'Pariatur aliquip culpa do veniam sit enim do fugiat commodo consectetur culpa ex minim. Id ipsum ipsum nostrud pariatur non. Occaecat dolor enim excepteur anim aute elit reprehenderit. Incididunt do quis esse adipisicing occaecat laborum et cillum.', NOW()),
    (44, 9, 'Brainclip', 'horse', 'shetland', 'https://via.placeholder.com/400/800/fff/?text=Brainclip', 'Duis proident aliquip do nulla id consequat amet qui. Voluptate consectetur Lorem elit veniam adipisicing non culpa anim aliquip dolor nulla nisi. Dolore aute id quis aliquip labore minim ad. Officia do laboris anim nostrud tempor laborum officia velit ut sint non voluptate laboris enim.', NOW()),
    (45, 8, 'Accel', 'horse', 'draft', 'https://via.placeholder.com/400/903/fff/?text=Accel', 'Sunt officia nostrud sit aliqua non quis. Laborum consectetur sint cillum sunt deserunt duis pariatur exercitation irure mollit. Exercitation ullamco consequat eu consequat exercitation nostrud consequat ad. Non ad voluptate irure veniam ea.', NOW()),
    (46, 8, 'Qaboos', 'horse', 'shetland', 'https://via.placeholder.com/400/867/fff/?text=Qaboos', 'Proident mollit enim ad incididunt Lorem id id officia aliqua ullamco magna excepteur officia. Consectetur magna velit aliquip commodo tempor culpa. Consequat labore magna amet aliquip ut sint consequat. Cillum cupidatat cupidatat deserunt est ea eiusmod qui ad.', NOW()),
    (47, 1, 'Qnekt', 'horse', 'draft', 'https://via.placeholder.com/400/850/fff/?text=Qnekt', 'Et dolore veniam duis commodo eiusmod Lorem id. Nostrud pariatur excepteur nostrud ad ex. Nisi culpa adipisicing ex mollit reprehenderit nostrud esse dolore. Et ad non Lorem culpa pariatur minim velit ad dolor mollit nulla ullamco esse ut.', NOW()),
    (48, 1, 'Voipa', 'horse', 'andalusian', 'https://via.placeholder.com/400/788/fff/?text=Voipa', 'Sint in ipsum in voluptate nisi nisi sint adipisicing ut culpa laborum id culpa cillum. Non aute veniam reprehenderit quis et culpa adipisicing non. Dolore in enim tempor eu dolore sunt. Duis cillum est labore commodo adipisicing esse in nulla cupidatat cupidatat nisi velit proident.', NOW()),
    (49, 3, 'Cincyr', 'cat', 'shorthair', 'https://via.placeholder.com/400/759/fff/?text=Cincyr', 'Tempor labore id dolor ad occaecat. Mollit nulla nisi incididunt reprehenderit ea aute aliquip. Anim do sit pariatur fugiat ut aute irure eu anim velit deserunt. Velit minim velit pariatur ea deserunt ea nisi reprehenderit voluptate cupidatat pariatur cupidatat magna occaecat.', NOW()),
    (50, 9, 'Wrapture', 'horse', 'shetland', 'https://via.placeholder.com/400/797/fff/?text=Wrapture', 'Magna sunt proident id ipsum dolor deserunt sint magna elit id proident. Fugiat et non ullamco duis sit non aliqua Lorem minim non est aute eu. Excepteur eu aliqua velit reprehenderit enim est proident. Esse do duis in amet Lorem id officia nostrud eu tempor.', NOW());